export const matchStats = [
  { value: "autoCycles", label: "Auto Cycles" },
  { value: "autoScored", label: "Auto Scored" },
  { value: "autoTop", label: "Auto Top" },
  { value: "autoMiddle", label: "Auto Middle" },
  { value: "autoBottom", label: "Auto Bottom" },
  { value: "teleopScored", label: "Teleop Scored" },
  { value: "teleopCycles", label: "Teleop Cycles" },
  { value: "teleopTop", label: "Teleop Top" },
  { value: "teleopMiddle", label: "Teleop Middle" },
  { value: "teleopBottom", label: "Teleop Bottom" },
  { value: "autoClimb", label: "Auto Climb Points" },
  { value: "teleopClimb", label: "Teleop Climb Points" },
  { value: "mobility", label: "Mobility" },
];

export const statLegend: any = {
  "Auto Cycles": "autoCycles",
  "Auto Scored": "autoScored",
  "Auto Top": "autoTop",
  "Auto Middle": "autoMiddle",
  "Auto Bottom": "autoBottom",
  "Teleop Scored": "teleopScored",
  "Teleop Cycles": "teleopCycles",
  "Teleop Top": "teleopTop",
  "Teleop Middle": "teleopMiddle",
  "Teleop Bottom": "teleopBottom",
  "Auto Climb Points": "autoClimb",
  "Teleop Climb Points": "teleopClimb",
  "Mobility": "mobility",
};
